### ISSUE TITLE
Improvement for the Archive page template

### ISSUE THREAD

**Issue by dziudek** [GavickPro/Meet-GavernWP#11]
for the **stuff.css** file new section 7.4:

``` css
/* 7.4. Archive page template
==================================== */

.archivepage .widget {
    float: left;
    margin: 0 2%;
    width: 29%;
}

.archivepage .widget.first {
    margin-left: 0;
    width: 31%;
}

.archivepage .widget.last {
    margin-right: 0;
    width: 31%;
}

.archivepage .widget li:before {
    display: none;
}

.archivepage .widget.first li {
    position: relative;
}

.archivepage .widget.first li a {
    display: block;
    padding-left: 54px;
}

.archivepage .widget li small {
    color: #aaa;
    left: 0;
    position: absolute;
    top: 7px;
}
```

it fixes a problem with the long post titles in the first column
