### ISSUE TITLE
Instead of -webkit-transform: translateZ(0);

### ISSUE THREAD

**Issue by dziudek** [GavickPro/Meet-GavernWP#142]
``` css
html {
    -webkit-font-smoothing: antialiased;
}
```
